#ifndef INC_PID_CONFIG_H_
#define INC_PID_CONFIG_H_

#define AUV_DEFAULT_PID_SP_P 1.5f
#define AUV_DEFAULT_PID_SP_I 0.1f
#define AUV_DEFAULT_PID_SP_D 0.05f
#define AUV_DEFAULT_PID_SP_MAXOUT 40.0f
#define AUV_DEFAULT_PID_SP_MINOUT -40.0f
#define AUV_DEFAULT_PID_SP_WRAPBOUND 0.0f

#define AUV_DEFAULT_PID_SS_P 0.8f
#define AUV_DEFAULT_PID_SS_I 0.1f
#define AUV_DEFAULT_PID_SS_D 0.05f
#define AUV_DEFAULT_PID_SS_MAXOUT 40.0f
#define AUV_DEFAULT_PID_SS_MINOUT -40.0f
#define AUV_DEFAULT_PID_SS_WRAPBOUND 0.0f

#endif /* INC_PID_CONFIG_H_ */
