#ifndef INC_TASK_CONFIG_H_
#define INC_TASK_CONFIG_H_

#define TASK_STATEESTIMATE_SLEEP_MS 1
#define TASK_CONTROL_SLEEP_MS 5
#define TASK_NCOM_SLEEP_MS 20
#define TASK_NCOM_PACKET_TIMEOUT_MS 50
#define TASK_NCOM_HANDSHAKE_TIMEOUT_MS 500
#define TASK_SENSOR_SLEEP_MS 100
#define TASK_SYSMONITOR_SLEEP_MS 50

/**
 * Application Timing Constants
 */
#define TASK_CONTROL_PID_DT 0.005f

#endif /* INC_TASK_CONFIG_H_ */
